#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  Workflow parameter file
# ----------------------------------------------------------------------------------------
# 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

---

# Main workflow options
input_files: '/home/jmrodriguezc/projects/nf-SearchEngine/tests/test1/raws/*.raw'
outdir: '/home/jmrodriguezc/projects/nf-SearchEngine/tests/test1/outdir'

# ------
# nf-SearchEngine: Search engine options
# ------

# ThermoRawFileParser options
thermo_parser_format: 2
# DecoyPYrat options
database_name: '/mnt/tierra/U_Proteomica/UNIDAD/DatosCrudos/jmrodriguezc/projects/nf-SearchEngine/tests/test1/dbs/human_202105_pro-sw.fasta'
add_decoys: true
decoy_prefix: 'DECOY_'
# MSFragger options
# (tsv, pin, pepxml, tsv_pin, tsv_pepxml, pepxml_pin, or tsv_pepxml_pin). Mandatory 'tsv' format.
msf_output_format: 'tsv_pepxml_pin'
