############################
# REFMOD PARAMETERS ------ #
############################

[General]
decimal_places = 6        # Number of decimal places to use in sequence+deltamass output columns

[Logging]
create_log = 1		        # Create log file, 0=no 1=yes
create_ini = 0		        # Create copy of INI file in input directory, 0=no 1=yes (specifying custom parameters in the command line will always create a copy of INI file)
create_summary = 1          # Create summary files containing metadata about each search

[Debug]
debug_scores = 0             # Report full score profiles for both MOD and HYB hyperscores (0 = No, 1 = Yes)

[Search]
batch_size = 1000           # Batch size
f_tol = 20.0                # Fragment mass tolerance (ppm)
dm_tol = 3.0                # Theoretical DM tolerance (Da)
score_mode = 0              # 0 = Sort by MOD-hyperscore, 1 = Sort by HYBRID-hyperscore
full_y = 1                  # 0 = Include the full y series up to yn for fragment matching, 1 = Exclude the y1 ion
preference = 0              # If the score is the same, prefer: 0 = Experimental DM, 1 = Theoretical DM

[Spectrum Processing]
top_n = 150                 # Maximum number of peaks (sorted by intensity) to keep from a spectrum
min_ratio = 0.01            # Remove peaks less intense than this multiple of the base peak intensity
bin_top_n = 0               # 0 = Off, 1 = Bin spectra according to average aminoacid mass (110 Da) and apply top_n filter to each bin
min_fragment_mz = 0.0       # Only use fragments with m/z bigger than this value
max_fragment_mz = 0.0       # Only use fragments with m/z smaller than this value. A value of 0 ignores this parameter.
deisotope = 0               # 0 = Off, 1 = Perform deisotoping

[FDR]
prot_column = proteins      # Name of column containing protein name
decoy_prefix = DECOY        # Decoy label
filter_target = 0           # Remove Decoys from output (0 = No, 1 = Yes).
filter_fdr = 0              # Remove PSMs with FDR above this value. A value of 0 ignores this parameter.

[Aminoacids]
A = 71.037114
R = 156.101111
N = 114.042927
D = 115.026943
C = 103.009185
E = 129.042593
Q = 128.058578
G = 57.021464
H = 137.058912
I = 113.084064
L = 113.084064
K = 128.094963
M = 131.040485
F = 147.068414
P = 97.052764
S = 87.032028
T = 101.047679
U = 150.953630
W = 186.079313
Y = 163.063329
V = 99.068414
O = 132.089878
Z = 129.042594

[Fixed Modifications]
Nt = 229.16293
Ct = 0
A = 0
R = 0
N = 0
D = 0
C = 57.021464 # Carbamidomethyl
E = 0
Q = 0
G = 0
H = 0
I = 0
L = 0
K = 229.16293     
M = 0
F = 0
P = 0
S = 0
T = 0
U = 0
W = 0
Y = 0
V = 0
O = 0
Z = 0

[Masses]
m_proton = 1.007276
m_hydrogen = 1.007825
m_oxygen = 15.994915

